package pack

// PackRule 加固特征规则
type PackRule struct {
	Sopath  []string
	Soname  []string
	Other   []string
	Soregex []string
	Jclass  []string
}

// PackRules 内置的加固规则映射表
var PackRules = map[string]PackRule{
	`appguard.us加固`: {
		Sopath: []string{`lib/arm64-v8a/libAppGuard.so`, `lib/arm64-v8a/libdiresu.so`},
		Soname: []string{`libloader.so`, `libAppGuard.so`, `libAppGuard-x86.so`, `libdiresu.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{`AppGuard$IOnLoadInformation`, `AppGuard$VersionInformation`, `Lcom/nhnent/appguard/AppGuard`},
	},
	`深盾安全加固（Virbox Protector）`: {
		Sopath: []string{},
		Soname: []string{`ibvirbox32.so`, `libvirbox64.so`},
		Other: []string{},
		Soregex: []string{`libvirbox..\.so`},
		Jclass: []string{},
	},
	`网秦加固（国信灵通）`: {
		Sopath: []string{},
		Soname: []string{`libnqshield.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`腾讯乐固（VMP）`: {
		Sopath: []string{`lib/arm64-v8a/libxgVipSecurity.so`, `lib/armeabi-v7a/libxgVipSecurity.so`},
		Soname: []string{`libxgVipSecurity.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`通付盾`: {
		Sopath: []string{},
		Soname: []string{`libNSaferOnly.so`, `libegis.so`, `libgeiri.so`, `libgeiri-x86.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`阿里加固`: {
		Sopath: []string{`assets/armeabi/libzuma.so`, `assets/libpreverify1.so`, `assets/libzuma.so`, `assets/libzumadata.so`},
		Soname: []string{`libzuma.so`, `libpreverify1.so`, `libmobisec.so`, `libsgmain.so`, `libsgsecuritybody.so`},
		Other: []string{`aliprotect.dat`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`顶像科技`: {
		Sopath: []string{`lib/armeabi/libx3g.so`, `lib/arm64-v8a/libsys_misc.so`},
		Soname: []string{`libx3g.so`, `libjni.so`, `libsys_misc.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`CFCA加固`: {
		Sopath: []string{},
		Soname: []string{`libbasec.so`, `libbasec_x86.so`, `libsecenh.so`, `libsecenh_a64.so`, `libsecenh_x86.so`},
		Other: []string{`my_classes.jar`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`爱加密`: {
		Sopath: []string{`assets/ijm_lib/armeabi/libexec.so`, `assets/ijm_lib/X86/libexec.so`, `lib/armeabi/libexecmain.so`},
		Soname: []string{`libexecmain.so`, `libexec.so`},
		Other: []string{`assets/af.bin`, `assets/signed.bin`, `ijiami.dat`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`腾讯云加固`: {
		Sopath: []string{`assets/libshellx-super.2021.so`, `lib/armeabi/libshell-super.2019.so`, `lib/armeabi/libshell-super.2020.so`, `lib/armeabi/libshell-super.2021.so`},
		Soname: []string{`libshell-super.2019.so`, `libshellx-super.2021.so`},
		Other: []string{`tencent_sub`},
		Soregex: []string{`libshellx\-super\.\d+\.so`, `libshell\-super\.\d+\.so`, `libshell\-superv(.*)\.\d{4}\.so`},
		Jclass: []string{},
	},
	`阿里云加固`: {
		Sopath: []string{},
		Soname: []string{`libdemolish.so`, `libdemolishdata.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`阿里聚安全`: {
		Sopath: []string{`assets/armeabi/libfakejni.so`, `assets/libpreverify1.so`, `assets/libzuma.so`, `assets/libzumadata.so`},
		Soname: []string{`libdemolish.so`, `libdemolishdata.so`, `libfakejni.so`, `libmobisec.so`, `libpreverify1.so`, `libsgmain.so`, `libsgsecuritybody.so`, `libzumadata.so`},
		Other: []string{`aliprotect.dat`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`360加固`: {
		Sopath: []string{`assets/libjiagu.so`},
		Soname: []string{`libjiagu.so`, `libjgdtc.so`, `libjgdtc_a64.so`, `libjgdtc_art.so`, `libjgdtc_x64.so`, `libjgdtc_x86.so`, `libjiagu.so`, `libjiagu_a64.so`, `libjiagu_art.so`, `libjiagu_ls.so`, `libjiagu_x64.so`, `libjiagu_x86.so`, `libprotectClass.so`, `libSafeManageService.so`},
		Other: []string{`assets/.appkey`},
		Soregex: []string{`libjiagu\_...\.so`, `libjgdtc\_...\.so`},
		Jclass: []string{},
	},
	`APKProtect`: {
		Sopath: []string{},
		Soname: []string{`libAPKProtect.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`OPPO安全检测SDK`: {
		Sopath: []string{`jni/arm64-v8a/libomesStdSco.so`, `jni/armeabi-v7a/libomesStdSco.so`, `jni/x86/libomesStdSco.so`, `jni/x86_64/libomesStdSco.so`},
		Soname: []string{`libomesStdSco.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`梆梆安全（定制版）`: {
		Sopath: []string{`lib/armeabi/DexHelper.so`},
		Soname: []string{`DexHelper.so`},
		Other: []string{`assets/classes.jar`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`爱加密5代壳`: {
		Sopath: []string{`assets/libijmDataEncryption.so`},
		Soname: []string{`libijmDataEncryption.so`},
		Other: []string{`assets/IJMDal.Data`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`腾讯加固`: {
		Sopath: []string{},
		Soname: []string{`libshell.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`google(play)加固`: {
		Sopath: []string{`lib/arm64-v8a/libpairipcore.so`, `lib/armeabi-v7a/libpairipcore.so`, `lib/x86_64/libpairipcore.so`, `lib/x86/libpairipcore.so`},
		Soname: []string{`libpairipcore.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`LIAPP加固`: {
		Sopath: []string{},
		Soname: []string{},
		Other: []string{`assets/LIAPP.ini`, `assets/pkgInfo.txt`},
		Soregex: []string{`com\..+UnityDataAssetPack.+\.apk$`, `com\..+AddressablesAssetPack.+\.apk$`},
		Jclass: []string{},
	},
	`未知厂商`: {
		Sopath: []string{},
		Soname: []string{`libapk-protect.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`apktoolplus`: {
		Sopath: []string{`lib/armeabi/libapktoolplus_jiagu.so`},
		Soname: []string{`libapktoolplus_jiagu.so`},
		Other: []string{`assets/jiagu_data.bin`, `assets/sign.bin`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`能信安科技`: {
		Sopath: []string{},
		Soname: []string{`libzprotect.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`娜迦加固（新版2022）`: {
		Sopath: []string{`lib/armeabi/libxloader.so`, `lib/armeabi-v7a/libxloader.so`, `lib/arm64-v8a/libxloader.so`},
		Soname: []string{`libxloader.so`},
		Other: []string{`assets/maindata/fake_classes.dex`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`瑞星加固`: {
		Sopath: []string{},
		Soname: []string{`librsprotect.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`网易易盾`: {
		Sopath: []string{},
		Soname: []string{`libnesec.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`腾讯御安全`: {
		Sopath: []string{`assets/libtosprotection.armeabi-v7a.so`, `assets/libtosprotection.armeabi.so`, `assets/libtosprotection.x86.so`, `lib/armeabi/libtest.so`, `lib/armeabi/libTmsdk-xxx-mfr.so`},
		Soname: []string{`libtosprotection.armeabi-v7a.so`, `libtosprotection.armeabi.so`, `libtosprotection.x86.so`},
		Other: []string{`assets/tosversion`},
		Soregex: []string{`libtosprotection\..+\.so`},
		Jclass: []string{},
	},
	`中国移动加固`: {
		Sopath: []string{`lib/armeabi/libcmvmp.so`, `lib/armeabi/libmogosec_dex.so`, `lib/armeabi/libmogosec_sodecrypt.so`, `lib/armeabi/libmogosecurity.so`},
		Soname: []string{`libcmvmp.so`, `libmogosec_dex.so`, `libmogosec_sodecrypt.so`, `libmogosecurity.so`, `ibmogosecurity.so`},
		Other: []string{`assets/mogosec_classes`, `assets/mogosec_data`, `assets/mogosec_dexinfo`, `assets/mogosec_march`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`爱加密企业版`: {
		Sopath: []string{},
		Soname: []string{},
		Other: []string{`assets/ijiami.ajm`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`百度加固`: {
		Sopath: []string{`lib/armeabi/libbaiduprotect.so`},
		Soname: []string{`libbaiduprotect.so`, `libbaiduprotect_art.so`, `libbaiduprotect_x86.so`},
		Other: []string{`assets/baiduprotect.jar`, `assets/baiduprotect1.jar`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`腾讯乐固（旧版）`: {
		Sopath: []string{`lib/armeabi/libshella-xxxx.so`, `lib/armeabi/libshellx-xxxx.so`},
		Soname: []string{`liblegudb.so`, `libshel1x.so`, `libshell.so`, `libshella-2.10.2.3.so`, `libshella-2.9.0.2.so`, `libshella-4.1.0.15.so`, `libshella-4.1.0.19.so`, `libshella.so`, `libshellx.so`, `libtup.so`},
		Other: []string{`lib/armeabi/mix.dex`, `lib/armeabi/mixz.dex`, `tencent_stub`},
		Soregex: []string{`libshella\-\d+\.\d+\.\d+\.\d+\.so`, `libWSSec(V?)\.so`},
		Jclass: []string{},
	},
	`腾讯手游加固`: {
		Sopath: []string{},
		Soname: []string{`libtprt.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`腾讯云移动应用安全（腾讯御安全）`: {
		Sopath: []string{},
		Soname: []string{`libBugly-yaq.so`, `libshell-super.2019.so`, `libshellx-super.2019.so`, `libzBugly-yaq.so`},
		Other: []string{`000000011111.dex`, `000000111111.dex`, `000001111111`, `00000o11111.dex`, `o0ooo000oo0o.dat`, `t86`, `tosprotection`, `tosversion`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`蛮犀加固`: {
		Sopath: []string{`assets/mxsafe/arm64-v8a/libdSafeShell.so`, `assets/mxsafe/x86_64/libdSafeShell.so`, `assets/mx/lib/arm64-v8a/libmxacc.so`, `assets/mx/lib/x86_64/libmxacc.so`},
		Soname: []string{`libdSafeShell.so`, `libmxacc.so`, `libmanxi.so`},
		Other: []string{`assets/mxsafe.config`, `assets/mxsafe.data`, `assets/mxsafe.jar`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`几维安全`: {
		Sopath: []string{`lib/armeabi/kdpdata.so`, `lib/armeabi/libkdp.so`, `lib/armeabi/libkwscmm.so`, `lib/arm64-v8a/libkadp.so`, `lib/arm64-v8a/libkiwi_dumper.so`, `lib/arm64-v8a/libkiwicrash.so`, `lib/arm64-v8a/libKwProtectSDK.so`, `lib/arm64-v8a/libkwdataenc.so`},
		Soname: []string{`kdpdata.so`, `libkdp.so`, `libkwscmm.so`, `libkwscr.so`, `libkwslinker.so`, `libkadp.so`, `libkiwi_dumper.so`, `libkiwicrash.so`, `libKwProtectSDK.so`, `libkwdataenc.so`},
		Other: []string{`assets/dex.dat`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`启明星辰`: {
		Sopath: []string{},
		Soname: []string{`libvenSec.so`, `libvenustech.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`娜迦加固`: {
		Sopath: []string{},
		Soname: []string{`libchaosvmp.so`, `libddog.so`, `libfdog.so`, `libhdog.so`},
		Other: []string{},
		Soregex: []string{`lib.dog\.so`},
		Jclass: []string{},
	},
	`梆梆安全（免费版）`: {
		Sopath: []string{`lib/armeabi/libSecShell-x86.so`, `lib/armeabi/libSecShell.so`},
		Soname: []string{`libSecShell_art.so`, `libSecShell.so`, `libSecShel1.so`, `libsecexe.so`, `libsecmain.so`},
		Other: []string{`assets/secData0.jar`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`珊瑚灵御`: {
		Sopath: []string{`assets/libreincp.so`, `assets/libreincp_x86.so`},
		Soname: []string{`libreincp.so`, `libreincp_x86.so`},
		Other: []string{},
		Soregex: []string{`libreincp\_...\.so`},
		Jclass: []string{},
	},
	`腾讯Bugly`: {
		Sopath: []string{`lib/arm64-v8a/libBugly.so`},
		Soname: []string{`libBugly.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`XAPK内嵌`: {
		Sopath: []string{},
		Soname: []string{},
		Other: []string{},
		Soregex: []string{`config\..+\.apk$`, `com\..+\..+\.apk$`},
		Jclass: []string{},
	},
	`娜迦加固（企业版）`: {
		Sopath: []string{},
		Soname: []string{`libedog.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`娜迦加固（开发者试用版-VMP）`: {
		Sopath: []string{},
		Soname: []string{`libvdog-x86.so`, `libvdog.so`},
		Other: []string{},
		Soregex: []string{`libvdog\-...\.so`},
		Jclass: []string{},
	},
	`爱加密3代壳`: {
		Sopath: []string{},
		Soname: []string{`libexecv3.so`},
		Other: []string{`assets/ijiami3.ajm`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`腾讯云移动应用安全`: {
		Sopath: []string{},
		Soname: []string{},
		Other: []string{`0000000lllll.dex`, `00000olllll.dex`, `000O00ll111l.dex`, `00O000ll111l.dex`, `0OO00l111l1l`, `o0oooOO0ooOo.dat`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`G-Presto加固`: {
		Sopath: []string{`lib/arm64-v8a/libATG_L.so`},
		Soname: []string{`libATG_D.so`, `libATG_H.so`, `libATG_L.so`},
		Other: []string{`assets/ATG_E.sec`, `assets/ATG_E_x64.sec`, `assets/ATG_E_x86.sec`, `assets/ATG_E_x86_64.sec`},
		Soregex: []string{},
		Jclass: []string{`Lcom/bishopsoft/Presto`, `Presto_Init`, `ATG_H init`},
	},
	`DexProtect加固`: {
		Sopath: []string{},
		Soname: []string{},
		Other: []string{`assets/classes.dex.dat`, `dp.arm-v7.so.dat`, `dp.arm.so.dat`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`OPPO应用加固`: {
		Sopath: []string{},
		Soname: []string{`OPPOProtect.so`, `OPPOProtect2019.so`},
		Other: []string{},
		Soregex: []string{`OPPOProtect\d\d\d\d\.so`},
		Jclass: []string{},
	},
	`UU安全加固`: {
		Sopath: []string{`assets/libuusafe.jar.so`, `assets/libuusafe.so`, `lib/armeabi/libuusafeempty.so`},
		Soname: []string{`libuusafe.jar.so`, `libuusafe.so`, `libuusafeempty.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
	`梆梆安全（企业版）`: {
		Sopath: []string{},
		Soname: []string{`libDexHelper-x86.so`, `libDexHelper.so`},
		Other: []string{},
		Soregex: []string{`libDexHelper\-...\.so`},
		Jclass: []string{},
	},
	`海云安加固`: {
		Sopath: []string{`lib/armeabi/libitsec.so`},
		Soname: []string{`libitsec.so`},
		Other: []string{`assets/itse`},
		Soregex: []string{},
		Jclass: []string{},
	},
	`盛大加固`: {
		Sopath: []string{},
		Soname: []string{`libapssec.so`},
		Other: []string{},
		Soregex: []string{},
		Jclass: []string{},
	},
}
